### ISSUE TITLE
Add support for xmega uC's.

### ISSUE THREAD

**Issue by sloped-soarer** [ZakKemble/AVRDUDESS#79] opened 2023-09-01 07:03 UTC
Hi.
Please can support for ATxmega parts be added.
E.g.
Fuses. fuse1, fuse2, fuse4 ....
Flash sections. boot, application, apptable.

Thanks.

**Comment by ZakKemble** [comment] 2024-01-14 16:41
Duplicate of #58

**Closed by ZakKemble** 2024-01-14 16:41 UTC
Labels: duplicate, ui change
